### PR TITLE
Update teaching time in 02-setup.md

### PR DESCRIPTION
**Pull request by kekoziar**
The additional SSH material takes at least 30 minutes to teach - some feedback is it takes ~45 minutes.

### CODE REVIEW

**Comment by srappel** [comment]
I agree. There was some discussion about whether this should happen in the setup instructions, but there's so much opportunity for error that it really needs to happen at the workshop, in my opinion.

I got a chuckle out of a quote in the instructor notes. Unfortunately, I don't think we can take their advice.

> If your learners are advanced enough to be comfortable with SSH, tell them they can use keys to authenticate on GitHub instead of passwords, but don’t try to set this up during class: it takes too long, and is a distraction from the core ideas of the lesson.

**Comment by tobyhodges** [comment]
> I got a chuckle out of a quote in the instructor notes. Unfortunately, I don't think we can take their advice.

😂  I think that Instructor Note needs to be removed.

**Review by sstevens2 — APPROVED** [review]
This change looks good to me!

**Comment by sstevens2** [comment]
Made a new issue with @srappel mention of the instructor note.  Think @tobyhodges is right about needing to remove it.

**Pull request merged**
